# Generated by Django 5.0.6 on 2024-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_forum', '0002_rename_content_answer_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Keyword',
            field=models.CharField(max_length=200),
        ),
    ]
