# Generated by Django 5.0.7 on 2024-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_forum', '0003_alter_question_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='answer_attachments/'),
        ),
    ]
