# Generated by Django 5.0.6 on 2024-07-15 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_skill_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureDevOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cplusplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title7', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Csharp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PowerBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selenium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('azuredevops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.azuredevops')),
                ('cplusplus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.cplusplus')),
                ('csharp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.csharp')),
                ('java', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.java')),
                ('powerbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.powerbi')),
                ('python', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.python')),
                ('rpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.rpa')),
                ('selenium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.selenium')),
            ],
        ),
    ]
